# IsaacGym config

# Environment settings
sim: isaacgym
robot: h1
task: humanoidbench:Stand
decimation: 4
num_envs: 128
add_table: false

# Training settings
train_or_eval: train
total_timesteps: 50_000_000
model_path: null
model_save_path: ./saved_models
model_save_freq: 1_000_000

# Eval settings
eval_model_path: <path to eval model>


# PPO parameters
learning_rate: 0.0003
n_steps: 256
num_batch: 64
n_epochs: 4

# Learning rate schedule
use_lr_schedule: true
lr_schedule_type: linear  # Optional: linear, constant, cosine
final_lr_fraction: 0.1    # Optional: final learning rate is 10% of initial learning rate

# Wandb settings
use_wandb: true
wandb_project: humanoidbench_rl_training

# visualization
headless: false
